version: "3.9"
services:
    redis:
        container_name: redis
        hostname: redis
        networks:
            - server-network
        image: redis
        ports:
            - 6379:6379

    mysql-test:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/mysql:/var/lib/mysql

    nginx-test:
        image: nginx:alpine
        container_name: nginx-test
        working_dir: /
        volumes:
            - ./:/test
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - server-network

    php-82-test:
        build: docker/php
        container_name: php82-test
        working_dir: /
        volumes:
            - ./:/test
        networks:
            - server-network

networks:
    server-network:
        external: true
